insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('G', '2', 'si', '工业硅期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'SH', '烧碱期权', null, null, 'CNY', 'CNY', '0', 30, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('G', '1', 'si', '工业硅', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'SH', '烧碱', null, null, 'CNY', 'CNY', '0', 30, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'PX', '对二甲苯期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'a', '黄大豆1号', null, null, 'CNY', 'CNY', '1', 10, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'b', '黄大豆2号', null, null, 'CNY', 'CNY', '1', 10, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('G', '2', 'lc', '碳酸锂期权', null, null, 'CNY', 'CNY', '0', 1, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'br', '丁二烯橡胶', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('N', '1', 'ec', '集运指数', null, null, 'CNY', 'CNY', '1', 50, '1', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'SA', '纯碱期权', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'bb', '细木工板', null, null, 'CNY', 'CNY', '0', 500, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'c', '黄玉米', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'c', '玉米期权', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'cs', '玉米淀粉', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'eb', '苯乙烯', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'eg', '乙二醇', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'fb', '纤维板', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'i', '铁矿石', null, null, 'CNY', 'CNY', '1', 100, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'i', '铁矿石期权', null, null, 'CNY', 'CNY', '0', 100, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'j', '冶金焦炭', null, null, 'CNY', 'CNY', '0', 100, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'jd', '鲜鸡蛋', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'jm', '焦煤', null, null, 'CNY', 'CNY', '0', 60, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'l', '线型低密度聚乙烯', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'l', '聚乙烯期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'lh', '生猪', null, null, 'CNY', 'CNY', '0', 16, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'm', '豆粕', null, null, 'CNY', 'CNY', '1', 10, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'm', '豆粕期权', null, null, 'CNY', 'CNY', '1', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'p', '棕榈油', null, null, 'CNY', 'CNY', '1', 10, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'p', '棕榈油期权', null, null, 'CNY', 'CNY', '1', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'pg', '液化石油气', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'pg', 'LPG期权', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'pp', '聚丙烯', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'pp', '聚丙烯期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'rr', '粳米', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'v', '聚氯乙烯', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'v', '氯乙烯期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'y', '豆油', null, null, 'CNY', 'CNY', '1', 10, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '1', 'IC', '中证500指数', '000905', null, 'CNY', 'CNY', '0', 200, '1', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '1', 'IF', '沪深300指数', '000300', null, 'CNY', 'CNY', '0', 300, '1', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '1', 'IH', '上证50指数', '000016', null, 'CNY', 'CNY', '0', 300, '1', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '2', 'IO', '沪深300股指期权', '000300', null, 'CNY', 'CNY', '0', 100, '1', '0', '2');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '1', 'T', '10年期国债期货', null, null, 'CNY', 'CNY', '0', 10000, '2', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '1', 'TF', '5年期国债期货', null, null, 'CNY', 'CNY', '0', 10000, '2', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '1', 'TS', '2年期国债期货', null, null, 'CNY', 'CNY', '0', 20000, '2', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('N', '1', 'bc', '国际铜', null, null, 'CNY', 'CNY', '1', 5, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('N', '1', 'lu', '低硫燃料油', null, null, 'CNY', 'CNY', '1', 10, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('N', '1', 'nr', '20号胶', null, null, 'CNY', 'CNY', '1', 10, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('N', '1', 'sc', '原油', null, null, 'CNY', 'CNY', '1', 1000, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('N', '2', 'sc', '原油期权', null, null, 'CNY', 'CNY', '1', 1000, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'ag', '白银', null, null, 'CNY', 'CNY', '0', 15, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'al', '铝', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'al', '铝期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'au', '黄金', null, null, 'CNY', 'CNY', '0', 1000, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'au', '黄金期权', null, null, 'CNY', 'CNY', '0', 1000, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'bu', '沥青', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'cu', '铜', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'cu', '铜期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'fu', '燃料油', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'hc', '热轧卷板', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'ni', '镍', null, null, 'CNY', 'CNY', '0', 1, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'pb', '铅', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'rb', '螺纹钢', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'ru', '天然橡胶', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'ru', '天胶期权', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'sn', '锡', null, null, 'CNY', 'CNY', '0', 1, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'sp', '漂针浆', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'ss', '不锈钢', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'wr', '线材', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'zn', '锌', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'zn', '锌期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'AP', '鲜苹果', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'CF', '一号棉花', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'CF', '棉花期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'CJ', '红枣', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'CY', '棉纱', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'FG', '玻璃', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'JR', '粳稻谷', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'LR', '晚籼稻', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'MA', '甲醇N', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'MA', '甲醇期权', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'OI', '菜籽油', null, null, 'CNY', 'CNY', '1', 10, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'PF', '短纤', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'PK', '花生', null, null, 'CNY', 'CNY', '1', 5, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'PM', '普通小麦', null, null, 'CNY', 'CNY', '0', 50, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'RI', '早籼稻', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'RM', '菜籽粕', null, null, 'CNY', 'CNY', '1', 10, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'RM', '菜籽粕期权', null, null, 'CNY', 'CNY', '1', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'RS', '油菜籽', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'SA', '纯碱', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'SF', '硅铁', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'SM', '锰硅', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'SR', '白砂糖', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'SR', '白糖期权', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'TA', '精对苯二甲酸', null, null, 'CNY', 'CNY', '1', 5, '0', '1', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'TA', 'PTA期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'UR', '尿素', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'WH', '优质强筋小麦', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'ZC', '动力煤N', null, null, 'CNY', 'CNY', '0', 100, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'ZC', '动煤期权', null, null, 'CNY', 'CNY', '0', 100, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '1', 'IM', '中证1000股指期货', '000852', null, 'CNY', 'CNY', '0', 200, '1', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '2', 'MO', '中证1000股指期权', '000852', null, 'CNY', 'CNY', '0', 100, '1', '0', '2');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'y', '豆油期权', null, null, 'CNY', 'CNY', '1', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'a', '黄大豆1号期权', null, null, 'CNY', 'CNY', '1', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'b', '黄大豆2号期权', null, null, 'CNY', 'CNY', '1', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'OI', '菜籽油期权', null, null, 'CNY', 'CNY', '1', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'PK', '花生期权', null, null, 'CNY', 'CNY', '1', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'PX', '对二甲苯', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '2', 'HO', '上证50股指期权', '000016', null, 'CNY', 'CNY', '0', 100, '1', '0', '2');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('J', '1', 'TL', '30年期国债期货', null, null, 'CNY', 'CNY', '0', 10000, '2', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '1', 'ao', '氧化铝', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('G', '1', 'lc', '碳酸锂', null, null, 'CNY', 'CNY', '0', 1, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'AP', '苹果期权', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'ag', '白银期权', null, null, 'CNY', 'CNY', '0', 15, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'eg', '乙二醇期权', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'eb', '苯乙烯期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'br', '丁二烯橡胶期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'PF', '短纤期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'SF', '硅铁期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'SM', '锰硅期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'UR', '尿素期权', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'rb', '螺纹钢期权', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '1', 'PR', '瓶片', null, null, 'CNY', 'CNY', '0', 15, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'PR', '瓶片期权', null, null, 'CNY', 'CNY', '0', 15, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('G', '1', 'ps', '多晶硅', null, null, 'CNY', 'CNY', '0', 3, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'CJ', '红枣期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'jd', '鸡蛋期权', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'cs', '玉米淀粉期权', null, null, 'CNY', 'CNY', '0', 10, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'ao', '氧化铝期权', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'pb', '铅期权', null, null, 'CNY', 'CNY', '0', 5, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'ni', '镍期权', null, null, 'CNY', 'CNY', '0', 1, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('S', '2', 'sn', '锡期权', null, null, 'CNY', 'CNY', '0', 1, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'lh', '生猪期权', null, null, 'CNY', 'CNY', '0', 16, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('G', '2', 'ps', '多晶硅期权', null, null, 'CNY', 'CNY', '0', 3, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('Z', '2', 'FG', '玻璃期权', null, null, 'CNY', 'CNY', '0', 20, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '1', 'lg', '原木', null, null, 'CNY', 'CNY', '0', 90, '0', '0', '1');

insert into t_product (EXCH_CODE, PRODUCT_TYPE, PRODUCT_ID, PRODUCT_NAME, UNDERLYING_ID, UNDERLYING_MULTIPLE, OFFER_CURRENCY, SETTLE_CURRENCY, IS_SPECIAL, VOLUME_MULTIPLE, MARKET_ID, IS_TRADERIGHT_SPECIAL, UNDERLYING_TYPE)
values ('D', '2', 'lg', '原木期权', null, null, 'CNY', 'CNY', '0', 90, '0', '0', '1');